# PARSEAMOS DRUGBANK

In [3]:
from funciones_BBDD import drugbank_enzimas as parse

xml_file = "./drugbank_all_full_database.xml/full_database.xml"
output_file = "enzimas.csv"

parse(xml_file, output_file)

Archivo guardado como: enzimas.csv

# IMPORTACIONES NECESARIAS

In [3]:
import pandas as pd

# EXPLORACION DE DATOS

In [15]:
df_enzimas = pd.read_csv ('enzimas.csv')

print("Drugs extracted:", len(df_enzimas["drug_name"].unique()))
df_enzimas.head()

Drugs extracted: 10162

,drugbank_id,drug_name,synonyms,type,gene_name,uniprot_id,action
0,DB00001,Lepirudin,"[Leu1, Thr2]-63-desulfohirudin|Desulfatohirudi...",target,F2,P00734,inhibitor
1,DB00002,Cetuximab,Cetuximab|Cétuximab|Cetuximabum|Chimeric MoAb ...,target,EGFR,P00533,binder
2,DB00002,Cetuximab,Cetuximab|Cétuximab|Cetuximabum|Chimeric MoAb ...,target,FCGR3B,O75015,binder
3,DB00002,Cetuximab,Cetuximab|Cétuximab|Cetuximabum|Chimeric MoAb ...,target,C1QA,P02745,binder
4,DB00002,Cetuximab,Cetuximab|Cétuximab|Cetuximabum|Chimeric MoAb ...,target,C1QB,P02746,binder

In [17]:
df_ATC_FDA = pd.read_csv ('ATC_FDA_N.csv')

print("Drugs extracted:", len(df_ATC_FDA["drug_name"].unique()))
df_ATC_FDA.head()

Drugs extracted: 19830

,drugbank_id,drug_name,fda_app_n,atc_codes
0,DB00001,Lepirudin,NDA020807,B01AE02
1,DB00002,Cetuximab,BLA125084|BLA125084,L01FE01
2,DB00003,Dornase alfa,BLA103532,R05CB13
3,DB00004,Denileukin diftitox,BLA761312|BLA103767,L01XX29
4,DB00005,Etanercept,BLA103795|BLA103795|BLA103795|BLA103795|BLA103...,L04AB01

In [25]:
df_hojas = pd.read_csv ('Medication Guides.csv')

print("Drugs extracted:", len(df_hojas["Drug Name"].unique()))
df_hojas.head()

Drugs extracted: 883

,Drug Name,Active Ingredient,Form;Route,Appl. No.,Company,Date,Link
0,Abacavir and LAmivudine,Abacavir Sulfate;Lamivudine,TABLET;ORAL,204311,MYLAN LABORATORIES LIMITED,12/22/2023,https://www.accessdata.fda.gov/drugsatfda_docs...
1,Abilify,Aripiprazole,SOLUTION;ORAL,21713,OTSUKA,02/05/2020,https://www.accessdata.fda.gov/drugsatfda_docs...
2,Abilify,Aripiprazole,"TABLET, ORALLY DISINTEGRATING;ORAL",21729,OTSUKA,02/05/2020,https://www.accessdata.fda.gov/drugsatfda_docs...
3,Abilify,Aripiprazole,TABLET;ORAL,21436,OTSUKA,01/22/2025,https://www.accessdata.fda.gov/drugsatfda_docs...
4,Abilify,Aripiprazole,INJECTABLE;INTRAMUSCULAR,21866,OTSUKA,02/05/2020,https://www.accessdata.fda.gov/drugsatfda_docs...

In [27]:
df_sidder = pd.read_csv ('sidder_cambio.csv')

print("Drugs extracted:", len(df_sidder["drug_name"].unique()))
df_sidder.head()

Drugs extracted: 935

           flat  drug_name         side_effect_se  freq_mean_y
0  CID100000085  carnitine         Abdominal pain     0.116000
1  CID100000085  carnitine  Gastrointestinal pain     0.116000
2  CID100000085  carnitine              Amblyopia     0.036667
3  CID100000085  carnitine                Anaemia     0.058000
4  CID100000085  carnitine     Decreased appetite     0.042500

# ENZIMAS

In [9]:
len(df_enzimas['drugbank_id'].unique())

10162

In [16]:
df_filtrado = df_enzimas[df_enzimas['drug_name'].str.contains('Cetuximab', na=False)]

In [18]:
print(df_filtrado)

  drugbank_id  drug_name                                           synonyms  \
1     DB00002  Cetuximab  Cetuximab|Cétuximab|Cetuximabum|Chimeric MoAb ...
2     DB00002  Cetuximab  Cetuximab|Cétuximab|Cetuximabum|Chimeric MoAb ...
3     DB00002  Cetuximab  Cetuximab|Cétuximab|Cetuximabum|Chimeric MoAb ...
4     DB00002  Cetuximab  Cetuximab|Cétuximab|Cetuximabum|Chimeric MoAb ...
5     DB00002  Cetuximab  Cetuximab|Cétuximab|Cetuximabum|Chimeric MoAb ...
6     DB00002  Cetuximab  Cetuximab|Cétuximab|Cetuximabum|Chimeric MoAb ...
7     DB00002  Cetuximab  Cetuximab|Cétuximab|Cetuximabum|Chimeric MoAb ...
8     DB00002  Cetuximab  Cetuximab|Cétuximab|Cetuximabum|Chimeric MoAb ...

     type gene_name uniprot_id  action
1  target      EGFR     P00533  binder
2  target    FCGR3B     O75015  binder
3  target      C1QA     P02745  binder
4  target      C1QB     P02746  binder
5  target      C1QC     P02747  binder
6  target    FCGR3A     P08637  binder
7  target    FCGR1A     P12314  binder
8  target    FCGR2A     P12318  binder

In [20]:
len(df_filtrado)

8

# DF SIDDER

In [7]:
df_sider = pd.read_csv ("sidder_cambio.csv")

In [9]:
df_sider.head()

           flat  drug_name         side_effect_se  freq_mean_y
0  CID100000085  carnitine         Abdominal pain     0.116000
1  CID100000085  carnitine  Gastrointestinal pain     0.116000
2  CID100000085  carnitine              Amblyopia     0.036667
3  CID100000085  carnitine                Anaemia     0.058000
4  CID100000085  carnitine     Decreased appetite     0.042500

In [11]:
len(df_sider)

59539