# IMPORTACIONES Y CSVS

In [2]:
import pandas as pd

enzimas = pd.read_csv("enzimas.csv")
excepciones = pd.read_csv("excepciones.csv")
sidder_atc = pd.read_csv("drug_atc.tsv", sep="\t", header=None, names=["flat", "drug_atc"])
sidder = pd.read_csv("sidder_eadv.csv")
codigos_ATC = pd.read_csv("ATC_DB.csv")

# Primero trato el csv de enzimas

In [4]:
#Como se hizo en el notebook de ejecucion de las bases de datos:

# Diccionario que cuenta cuantas encimas tengo de cada y cuales son el top 5 con las que me quedare
diccionario_enzimas = (
    enzimas[enzimas["type"] == "enzyme"]["gene_name"]
    .value_counts()
    .to_dict()
)

print(diccionario_enzimas)
# Por tanto escogemos las que se metabolizan por cualquiera de las siguientes enzimas ["CYP2D6", "CYP3A4", "CYP3A5", "CYP2C19", "CYP2C9", "CYP1A2"] 
#que son las top 5 y CYP3A5 porque va con CYP3A4 (explicar mejor) y las target porque aunque no den problemas por las interacciones son posibles 
#opciones de reemplazo de principio activo
target_top5 = enzimas[
    ((enzimas["type"] == "enzyme") & (enzimas["gene_name"].isin(["CYP2D6", "CYP3A4", "CYP3A5", "CYP2C19", "CYP2C9", "CYP1A2"])))
    |       #or
    (enzimas["type"] == "target")
]
#Elimino la columna de sinonimos y de uniprot_id
target_top5 = target_top5.drop(columns=["synonyms", "uniprot_id"])
# Renombro las columnas 
target_top5.columns = ["DrugBank_id", "Drug_name", "Tipo", "Gene_name", "Accion"]
target_top5.head()

{'CYP3A4': 1119, 'CYP2C9': 435, 'CYP2D6': 432, 'CYP1A2': 385, 'CYP2C19': 350, 'CYP2C8': 336, 'CYP3A5': 297, 'CYP2B6': 232, 'UGT1A1': 148, 'CYP2E1': 144, 'CYP3A7': 128, 'CYP1A1': 112, 'UGT1A9': 86, 'CYP2A6': 85, 'UGT2B7': 84, 'BCHE': 61, 'UGT1A3': 58, 'CYP1B1': 45, 'CYP19A1': 42, 'MAOA': 40, 'UGT1A4': 32, 'CES1': 32, 'PTGS1': 31, 'PTGS2': 29, 'CYP2C18': 29, 'MAOB': 24, 'UGT1A8': 23, 'CYP2J2': 23, 'MPO': 22, 'XDH': 22, 'AOX1': 21, 'UGT2B4': 20, 'FMO3': 19, 'UGT2B15': 19, 'UGT1A10': 18, 'UGT1A6': 18, 'CYP11B1': 17, 'COMT': 16, 'CYP3A43': 15, 'SULT1A1': 14, 'CYP4A11': 13, 'CBR1': 13, 'CYP11B2': 13, 'UGT2B17': 12, 'UGT1A7': 12, 'SOD1': 12, 'GSTP1': 12, 'DCK': 12, 'GSTA1': 11, 'FMO1': 11, 'POR': 11, 'HSD11B1': 11, 'GSTM1': 10, 'CYP11A1': 10, 'NAT2': 10, 'CYP4F2': 10, 'NME1': 10, 'IDE': 10, 'CES2': 10, 'PLA2G4A': 9, 'SULT1A3': 8, 'ADA': 8, 'GSTA2': 8, 'AMY2A': 8, 'DDC': 8, 'CYP17A1': 8, 'NQO1': 8, 'ACHE': 8, 'GLUL': 7, 'CYP2A13': 7, 'MTHFR': 7, 'TYMP': 7, 'UGT2B10': 7, 'ALOX5': 7, 'ALDH2': 7, 'CES1A1a': 7, 'CDA': 6, 'DBH': 6, 'AKR1C3': 6, 'AKR1C1': 6, 'SRD5A1': 6, 'SULT1E1': 6, 'HSD11B2': 6, 'CYP24A1': 6, 'AKR1A1': 5, 'Cyp3a2': 5, 'SULT2A1': 5, 'GSTT1': 5, 'AKR1C4': 5, 'DHFR': 5, 'PROC': 5, 'PON1': 5, 'NME2': 5, 'DPEP1': 5, 'TPMT': 5, 'CYP2B': 5, 'CYP27A1': 5, 'ADH5': 5, 'ADK': 4, 'AKR1B1': 4, 'CBR3': 4, 'AK2': 4, 'GSTM3': 4, 'HSD3B2': 4, 'PGD': 4, 'HMOX1': 4, 'CMPK1': 4, 'GPX1': 4, 'ADH1C': 4, 'AKR1C2': 4, 'PON3': 4, 'Cyp3a1': 4, 'CYP27B1': 4, 'bla': 3, 'F2': 3, 'GUCY1A2': 3, 'GCK': 3, 'HK1': 3, 'DPP4': 3, 'aac': 3, 'NAT1': 3, 'NOS3': 3, 'SULT1B1': 3, 'CTSA': 3, 'CKB': 3, 'AK1': 3, 'FAAH': 3, 'AOC1': 3, 'TXNRD1': 3, 'MT2A': 3, 'MT1A': 3, 'nat': 3, 'SOD2': 3, 'HNMT': 3, 'TDO2': 3, 'CYP2R1': 3, 'ADH6': 3, 'ALOX15': 3, 'CPE': 3, 'ALPL': 3, 'CAT': 3, 'GCLC': 3, 'GSTO1': 3, 'FADS1': 3, 'eno': 3, 'CHAT': 2, 'F10': 2, 'CHKA': 2, 'CEPT1': 2, 'GSR': 2, 'CHKB': 2, 'CHDH': 2, 'PGK1': 2, 'FADS2': 2, 'TK': 2, 'PCYT1A': 2, 'PLD1': 2, 'ADAMTS13': 2, 'GUK1': 2, 'CYBRD1': 2, 'TYMS': 2, 'UPP2': 2, 'UPP1': 2, 'DPYD': 2, 'CA2': 2, 'SAT1': 2, 'CAD': 2, 'SULT1A2': 2, 'PNMT': 2, 'AKR1D1': 2, 'ALPG': 2, 'MT-CO1': 2, 'LOX': 2, 'ANPEP': 2, 'STS': 2, 'MME': 2, 'ddn': 2, 'PAH': 2, 'GUSB': 2, 'HSD3B1': 2, 'Cyp1a1': 2, 'CA1': 2, 'ARSA': 2, 'SULT1C4': 2, 'HPSE': 2, 'GLS2': 2, 'ADH4': 2, 'AMACR': 2, 'CYP4F12': 2, 'VKORC1': 2, 'GAA': 2, 'ELANE': 2, 'MGST2': 2, 'NOS2': 2, 'AKR1B10': 2, 'GLS': 2, 'ADH7': 2, 'PRODH': 2, 'ADH1A': 2, 'AK4': 2, 'CYP4B1': 2, 'HPRT1': 2, 'BCAT1': 2, 'ADH1B': 2, 'GGH': 2, 'GMPS': 2, 'CYP26A1': 2, 'Cyp2c6': 2, 'Cyp2b1': 2, 'IDO1': 2, 'Cyp2c11': 2, 'TK1': 2, 'DGUOK': 2, 'TGM6': 2, 'EPHX1': 2, 'cat3': 2, 'ELOVL4': 1, 'IDUA': 1, 'BLVRB': 1, 'assT': 1, 'HMGCR': 1, 'PDE5A': 1, 'ACSS2': 1, 'PDXK': 1, 'HEXB': 1, 'GALNS': 1, 'IDS': 1, 'TPK1': 1, 'ARSB': 1, 'ENOPH1': 1, 'ENTPD5': 1, 'IDH1': 1, 'pfkA': 1, 'PCK1': 1, 'PRDX1': 1, 'NAGS': 1, 'ITIH1': 1, 'ACOX1': 1, 'PRDX5': 1, 'SULT1C2': 1, 'MMP12': 1, 'DGAT2': 1, 'ACO1': 1, 'NAGLU': 1, 'WARS2': 1, 'PGM1': 1, 'TPH1': 1, 'TPH2': 1, 'WARS1': 1, 'ADAMTS4': 1, 'CEMIP2': 1, 'SPHK1': 1, 'PNLIP': 1, 'HINT1': 1, 'ATP5F1B': 1, 'ACE2': 1, 'PRNP': 1, 'AANAT': 1, 'CRYZ': 1, 'ALDH5A1': 1, 'ADHFE1': 1, 'NNT': 1, 'PDXP': 1, 'DIO1': 1, 'DIO2': 1, 'DIO3': 1, 'THTPA': 1, 'TYR': 1, 'PAM': 1, 'ANG': 1, 'ALDH1A1': 1, 'TGM2': 1, 'TST': 1, 'GSTA3': 1, 'FXYD2': 1, 'Cyp2a1': 1, 'ABL1': 1, 'ATP5F1D': 1, 'ADCY1': 1, 'PFKFB1': 1, 'ATP1A1': 1, 'F8': 1, 'PLA2G10': 1, 'LPL': 1, 'tgt': 1, 'PDGFRA': 1, 'GSTM5': 1, 'TSTD1': 1, 'GSTT2': 1, 'GSTZ1': 1, 'MGST1': 1, 'MGST3': 1, 'TOP1': 1, 'CTSB': 1, 'CTSL': 1, 'Cyp2c12': 1, 'SPR': 1, 'ALPI': 1, 'AADAC': 1, 'PLAT': 1, 'VARS1': 1, 'HEPH': 1, 'TF': 1, 'HAMP': 1, 'RPE': 1, 'SOAT1': 1, 'onr': 1, 'CPA1': 1, 'BCO1': 1, 'SCLY': 1, 'LYZ': 1, 'MTR': 1, 'ELOVL5': 1, 'blaZ': 1, 'ERBB2': 1, 'POU2F2': 1, 'SLC47A1': 1, 'SLC27A2': 1, 'NUAK2': 1, 'CYP4F3': 1, 'SMPD1': 1, 'ALDH3A2': 1, 'CPA6': 1, 'PRSS1': 1, 'C1S': 1, 'C1R': 1, 'PCCB': 1, 'tetX2': 1, 'CP': 1, 'CPS1': 1, 'ACY1': 1, 'NQO2': 1, 'trpS': 1, 'MMAB': 1, 'APRT': 1, 'PCYT2': 1, 'NT5C': 1, 'MAT2A': 1, 'MSRB2': 1, 'LNPEP': 1, 'BLMH': 1, 'SRD5A2': 1, 'mtlD': 1, 'MT-ND1': 1, 'OXA-10': 1, 'HPGD': 1, 'PREP': 1, 'PKLR': 1, 'SUCLA2': 1, 'PCK2': 1, 'ADSS1': 1, 'NT5C2': 1, 'PCSK1': 1, 'PCSK2': 1, 'MAT1A': 1, 'NT5E': 1, 'DCTD': 1, 'NUDT15': 1, 'IMPDH1': 1, 'IMPDH2': 1, 'cobU': 1, 'SRM': 1, 'AMPD1': 1, 'PHOSPHO1': 1, 'cat': 1, 'F13A1': 1, 'SAT2': 1, 'TGM5': 1, 'TK2': 1, 'TGM1': 1, 'EGFR': 1, 'TGM4': 1, 'TGM3': 1, 'TGM7': 1, 'UMPS': 1, 'PPAT': 1, 'FPGS': 1, 'SLC29A1': 1, 'ATIC': 1, 'cpg2': 1, 'ASNS': 1, 'PLD2': 1, 'PLA2G2A': 1, 'KYAT1': 1, 'PFAS': 1, 'GATB': 1, 'GFPT2': 1, 'QARS1': 1, 'PNP': 1, 'NADSYN1': 1, 'ITPA': 1, 'NDUFS2': 1, 'NDUFS3': 1, 'GLDC': 1, 'OXCT1': 1, 'choB': 1, 'ASPH': 1, 'AMT': 1, 'BAAT': 1, 'mdlC': 1, 'pox5': 1, 'PNPO': 1, 'pdxP': 1, 'FLAD1': 1, 'HDAC1': 1, 'CDO1': 1, 'ST3GAL5': 1, 'HSD17B1': 1, 'SLC22A6': 1, 'SLC22A8': 1, 'SLCO1B3': 1, 'DLD': 1, 'PTGR1': 1, 'TPO': 1, 'CYP7A1': 1, 'CYP21A2': 1, 'AKR1E2': 1, 'ABCB1': 1, 'GCSH': 1, 'FNR': 1, 'SULT2B1': 1, 'P3H3': 1, 'NDUFS7': 1, 'ASMT': 1, 'NOS1': 1, 'MSRB1': 1, 'MSRA': 1, 'ureC': 1, 'MARS1': 1, 'azr': 1, 'MARS2': 1, 'UBIAD1': 1, 'MAT2B': 1, 'BHMT2': 1, 'SDHC': 1, 'blm': 1, 'FASN': 1, 'KPC-2': 1, 'SDHA': 1, 'SUCLG2': 1, 'CYP51A1': 1, 'P4HA1': 1, 'PLOD3': 1, 'knt': 1, 'aphA1': 1, 'P3H1': 1, 'penP': 1, 'CYP7B1': 1, 'tynA': 1, 'P3H2': 1, 'PLAU': 1}

  DrugBank_id  Drug_name    Tipo Gene_name     Accion
0     DB00001  Lepirudin  target        F2  inhibitor
1     DB00002  Cetuximab  target      EGFR     binder
2     DB00002  Cetuximab  target    FCGR3B     binder
3     DB00002  Cetuximab  target      C1QA     binder
4     DB00002  Cetuximab  target      C1QB     binder

In [5]:
# VER SI HAY NULOS
target_top5.isna().any()

DrugBank_id    False
Drug_name      False
Tipo           False
Gene_name       True
Accion          True
dtype: bool

In [6]:
#Hay nulos en accion cuando solo hay enzimas y no targets, por tanto se tendra en cuenta
comprobacion = target_top5[target_top5["Tipo"]=="enzyme"]
print(comprobacion.head())
comprobacion.isna().any()

   DrugBank_id              Drug_name    Tipo Gene_name     Accion
28     DB00008  Peginterferon alfa-2a  enzyme    CYP1A2  inhibitor
36     DB00011     Interferon alfa-n1  enzyme    CYP1A2  inhibitor
58     DB00018     Interferon alfa-n3  enzyme    CYP1A2  inhibitor
68     DB00022  Peginterferon alfa-2b  enzyme    CYP1A2  inhibitor
69     DB00022  Peginterferon alfa-2b  enzyme    CYP2D6  inhibitor

DrugBank_id    False
Drug_name      False
Tipo           False
Gene_name      False
Accion          True
dtype: bool

### TRATO LOS CODIGOS ATC QUE OBTUVIMOS DESPUES

In [8]:
# Eliminamos la columna que corresponde a el nombre para no repetir cuando unamos
codigos_ATC = codigos_ATC.drop(columns=["drug_name"])
# Elimino los que como codigo ATC aparezca Nan para separarlos
codigos_ATC = codigos_ATC.dropna(subset=['atc_codes'])

#Como un drug name puede tener mas de un codigo ATC los separo en diferentes filas
separado = codigos_ATC["atc_codes"].str.split(r"\|")
#Donde almaceno las filas
rows = []
#identificador de la fila donde me llego
i = 0
#Por cada codigo
for cods in separado:
    fila = codigos_ATC.iloc[i]
    if len(cods)!=1:
        d_id = fila["drugbank_id"]
        for uno in cods:
            rows.append([d_id, uno])
    else:
        rows.append(fila.tolist())
    i+=1

#Cambio los nombres para estandarizarlo
ATC_separado = pd.DataFrame(rows, columns=[
        "DrugBank_id",
        "Drug_ATC"
    ])
ATC_separado.head()

  DrugBank_id Drug_ATC
0     DB00001  B01AE02
1     DB00002  L01FE01
2     DB00003  R05CB13
3     DB00004  L01XX29
4     DB00005  L04AB01

In [9]:
# Ver si hay nulos
ATC_separado.isna().any()

DrugBank_id    False
Drug_ATC       False
dtype: bool

### Uno ambos DF para crear el de drugbank

In [11]:
#Por la derecha porque quiero que se me queden todos los que tiene DB
drugbank = pd.merge (ATC_separado, target_top5, on="DrugBank_id", how="right")
print(drugbank.shape)
drugbank.head()

(38466, 6)

  DrugBank_id Drug_ATC  Drug_name    Tipo Gene_name     Accion
0     DB00001  B01AE02  Lepirudin  target        F2  inhibitor
1     DB00002  L01FE01  Cetuximab  target      EGFR     binder
2     DB00002  L01FE01  Cetuximab  target    FCGR3B     binder
3     DB00002  L01FE01  Cetuximab  target      C1QA     binder
4     DB00002  L01FE01  Cetuximab  target      C1QB     binder

### Añado la columna: Prioridad

In [13]:
# Del df de enzimas nos quedamos solo con las top 5
top_5 = enzimas[enzimas["gene_name"].isin(["CYP2D6", "CYP3A4", "CYP3A5", "CYP2C19", "CYP2C9", "CYP1A2"])]
# Y de esas solo con las duplicadas que significa que tienen mas de una enzima
duplicados = top_5[top_5.duplicated(subset="drugbank_id", keep=False)]
print(len(duplicados["drugbank_id"].unique()))

#De las que hemos querido establecer prioridad son:
problematicas = duplicados["drug_name"].unique().tolist()

#Añadimos la columna prioridad
#Para todas las que se metabolizan por una enzima (las que no son problemáticas) ponemos 1 
#En este caso tambien se le pone a los target pero como no los usamos luego, es indiferente
drugbank["Prioridad"] = drugbank["Drug_name"].apply(
    lambda x: 1 if x not in problematicas else None
)
#Lo junto con las excepciones que hemos podido obtener
DDI_prioridad = drugbank.merge(excepciones, how="left", on=["Drug_name", "Gene_name"])
DDI_prioridad.head()

755

,DrugBank_id,Drug_ATC,Drug_name,Tipo,Gene_name,Accion,Prioridad_x,Prioridad_y
0,DB00001,B01AE02,Lepirudin,target,F2,inhibitor,1.0,NaN
1,DB00002,L01FE01,Cetuximab,target,EGFR,binder,1.0,NaN
2,DB00002,L01FE01,Cetuximab,target,FCGR3B,binder,1.0,NaN
3,DB00002,L01FE01,Cetuximab,target,C1QA,binder,1.0,NaN
4,DB00002,L01FE01,Cetuximab,target,C1QB,binder,1.0,NaN

In [14]:
# Unimos x e y
DDI_prioridad["Prioridad"] = DDI_prioridad["Prioridad_x"].fillna(DDI_prioridad["Prioridad_y"])
DDI_prioridad= DDI_prioridad.drop(columns=["Prioridad_x", "Prioridad_y"])
DDI_prioridad.head()
#Rellenamos los que aun son nulos con 0 porque:
# son de los que: o no hemos podido obtener prioridad, o habia otra enzima que notebookLM identifico como principal de las que no tengo en cuenta
DDI_prioridad["Prioridad"] = DDI_prioridad["Prioridad"].fillna(0)
#Porsiacaso
DDI_prioridad = DDI_prioridad.drop_duplicates()
DDI_prioridad.isna().any()

DrugBank_id    False
Drug_ATC        True
Drug_name      False
Tipo           False
Gene_name       True
Accion          True
Prioridad      False
dtype: bool

In [15]:
#LO GUARDO
DDI_prioridad.to_csv("DDI_sea.csv", index=False)

# UNO AL DF DE SIDDER LOS CODIGOS ATC 
Es para poder correlacionar csvs de alguna manera

In [17]:
efectos_adversos = pd.merge (sidder_atc, sidder, on="flat", how="inner")
# Sin nulos
efectos_adversos.isna().any()

flat              False
drug_atc          False
drug_name         False
side_effect_se    False
freq_mean_y       False
dtype: bool

In [18]:
#liminamos la columna de flat que no usaremos
efectos_adversos = efectos_adversos.drop(columns=["flat"])
#Cambio los nombres de las columnas para estandarizar
efectos_adversos.columns = ["Drug_ATC","Drug_name","Side_effect","Freq_media"]
efectos_adversos.head()

  Drug_ATC  Drug_name            Side_effect  Freq_media
0  A16AA01  carnitine         Abdominal pain    0.116000
1  A16AA01  carnitine  Gastrointestinal pain    0.116000
2  A16AA01  carnitine              Amblyopia    0.036667
3  A16AA01  carnitine                Anaemia    0.058000
4  A16AA01  carnitine     Decreased appetite    0.042500

In [19]:
#Lo guardo
efectos_adversos.to_csv("efectos_adversos.csv", index=False)